// Generated by CoffeeScript 1.6.3
(function() {
  var crypto;

  crypto = require('crypto');

  exports.encrypt = function(password) {
    return crypto.createHash('md5').update(password).digest('hex');
  };

  exports.compare = function(password, userPassword, cb) {
    if (this.encrypt(password) === userPassword) {
      return cb(true);
    } else {
      return cb(false);
    }
  };

}).call(this);
