// Generated by CoffeeScript 1.6.2
(function() {
  var app, config, express, fs, io, models, mongoose, passport, port, server;

  express = require('express');

  app = express();

  server = require('http').createServer(app);

  passport = require('passport');

  config = require('./config/config');

  io = require('socket.io').listen(server);

  fs = require('fs');

  mongoose = require('mongoose');

  mongoose.connect(config.dbURI);

  models = __dirname + '/models';

  fs.readdirSync(models).forEach(function(file) {
    return require(models + '/' + file);
  });

  require('./config/passport')(passport, config);

  require('./config/express')(app, passport);

  require('./config/routes')(app, passport);

  io.sockets.on('connection', function(socket) {
    return socket.emit('hello', {
      data: 'Hi!'
    });
  });

  port = process.env.PORT || 3000;

  server.listen(port, function() {
    return console.log("Server running on port " + port);
  });

}).call(this);
