// Generated by CoffeeScript 1.6.1
(function() {
  var app, express, fs, io, port, server;

  fs = require('fs');

  express = require('express');

  app = express();

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  app.configure(function() {
    app.set('views', __dirname + '/../views');
    app.set('view engine', 'jade');
    app.set('view options', {
      layout: false
    });
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"](__dirname + '/../public'));
  });

  app.get('/', function(req, res) {
    return res.sendfile('./views/index.html');
  });

  io.sockets.on('connection', function(socket) {
    return socket.emit('hello', {
      data: 'Hi!'
    });
  });

  port = process.env.PORT || 3000;

  server.listen(port, function() {
    return console.log("Listening on port " + port);
  });

}).call(this);
