// Generated by CoffeeScript 1.6.2
(function() {
  var User, mongoose;

  mongoose = require('mongoose');

  User = mongoose.model('User');

  module.exports.index = function(req, res) {
    return res.render('index');
  };

}).call(this);
