// Generated by CoffeeScript 1.6.2
(function() {
  var User, mongoose, passwords;

  passwords = require('../modules/passwords');

  mongoose = require('mongoose');

  User = mongoose.model('User');

  module.exports.createAccount = function(req, res) {
    var body, user,
      _this = this;

    body = req.body;
    if (!body.name || !body.email || !body.pass1 || !body.pass2 || body.pass1 !== body.pass2) {
      res.send(JSON.stringify({
        error: 'Please complete the form'
      }));
      return;
    }
    user = {};
    user.linkedID = null;
    user.firstName = body.name.split(' ')[0];
    user.lastName = body.name.split(' ')[1];
    user.fullName = body.name;
    user.primaryEmail = body.email;
    user.emails = [body.email];
    user.avatar = '';
    return passwords.encrypt(body.pass1, function(err, pass) {
      var userModel;

      if (!err) {
        user.password = pass;
        userModel = new User(user);
        return userModel.save(function(err) {
          var _this = this;

          if (err) {
            return res.send(JSON.stringify({
              error: 'An error occured. Please try again.'
            }));
          } else {
            return req.logIn(userModel, function(err) {
              if (err) {
                return next(err);
              }
              return res.redirect('/');
            });
          }
        });
      } else {
        return res.send(JSON.stringify({
          error: 'An error occured. Please try again.'
        }));
      }
    });
  };

}).call(this);
