// Generated by CoffeeScript 1.6.2
(function() {
  var development, env;

  development = {
    env: global.process.env.NODE_ENV || 'development',
    baseURI: 'http://localhost:3000',
    dbURI: 'mongodb://localhost/'
  };

  env = development;

  if (global.process.env.NODE_ENV === 'production') {
    env = production;
  } else if (global.process.env.NODE_ENV === 'staging') {
    env = staging;
  }

  module.exports = env;

}).call(this);
