// Generated by CoffeeScript 1.6.2
(function() {
  var FacebookStrategy, LocalStrategy, mongoose, passwords;

  mongoose = require('mongoose');

  passwords = require('../modules/passwords');

  LocalStrategy = require('passport-local').Strategy;

  FacebookStrategy = require('passport-facebook').Strategy;

  module.exports = function(passport, config) {
    passport.serializeUser(function(user, done) {
      return done(null, user);
    });
    passport.deserializeUser(function(obj, done) {
      return done(null, obj);
    });
    return passport.use(new LocalStrategy(function(email, pass, done) {}));
  };

}).call(this);
