// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(app, passport) {
    var index;

    index = require('../controllers/index');
    return app.get('/', index.index);
  };

}).call(this);
