// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(app, passport) {
    var auth, index, users;

    index = require('../controllers/index');
    app.get('/', index.index);
    auth = require('../controllers/auth');
    app.get('/login', auth.login);
    app.post('/auth', passport.authenticate('local', {
      failureRedirect: '/login'
    }), auth.auth);
    app.get('/logout', auth.logout);
    users = require('../controllers/users');
    return app.post('/createaccount', users.createAccount);
  };

}).call(this);
