// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app, passport) {
    var auth, index, routeMiddleware, users;
    routeMiddleware = function(req, res, next) {
      res.locals.user = req.user;
      res.locals.ENV = global.process.env.NODE_ENV;
      if (req.isAuthenticated()) {
        return next();
      }
      res.redirect("/login");
      return next();
    };
    index = require('../controllers/index');
    app.get('/', index.index);
    auth = require('../controllers/auth');
    app.get('/login', auth.login);
    app.post('/auth', passport.authenticate('local', {
      failureRedirect: '/login'
    }), auth.auth);
    app.get('/logout', auth.logout);
    users = require('../controllers/users');
    return app.post('/createaccount', users.createAccount);
  };

}).call(this);
